config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'actives#index'
  resources :actives do 
    resources :comments
  end
  resources :tags
end

app/models/active.rb
class Active < ApplicationRecord
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_one_attached :photo

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end
end  

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :active
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :actives, through: :taggings
  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  # tags = active.taggings.collect{|tagging| tagging.tag}
  belongs_to :tag
  belongs_to :active
end

app/controllers/actives_controller.rb
class ActivesController < ApplicationController
	include ActivesHelper

  def index
    @actives = Active.all
  end

	def show
		@active = Active.find(params[:id])
	end

	def new 
		@active = Active.new
	end

	def create
		@active = Active.new(active_params)
		@active.title = params[:active][:title]
		@active.save
		flash.notice ="Active  '#{@active.title}' Created!"
		redirect_to active_path(@active)
	end

	def destroy
		@active = Active.find(params[:id])
		@active.destroy

		redirect_to root_path, status: :see_other
	end

	def edit
		@active = Active.find(params[:id])
	end

	def update
		@active = Active.find(params[:id])
		@active.update(active_params)
		flash.notice ="Active  '#{@active.title}' Updated!"
		redirect_to active_path(@active)
	end

  def comment
	  @comment = Comment.new
    @comment.active_id = @active.id
	end


	def active_params
		params.require(:active).permit(:title, :body, :tag_list, :photo)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.active_id = params[:active_id]
  
    @comment.save
  
    redirect_to active_path(@comment.active)
  end
  
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/actives_helper.rb
module ActivesHelper

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/actives/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
</div>
<p>Posted <%= distance_of_time_in_words(comment.active.created_at, comment.created_at) %> later</p>

app/views/actives/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for(@active, html: {multipart: true}) [ @active, @comment ] do |f| %>
  <p>
    <%= f.label :author_name %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <%# if @active.image.exists? %>
        <%#= image_tag @active.image.url %><br/>
    <%# end %>
    <%#= f.label :image, "Attach a New Image" %><br />
    <%#= f.file_field :image %>
  </p>

  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/actives/edit.html.erb
<h1>Edit an Active</h1>

<%= form_for(@active) do |f| %>
  <ul>
  <% @active.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/actives/index.html.erb
<h1>All Actives</h1>

<ul id="actives">
  <% @actives.each do |active| %>
    <li>
      <%= link_to active.title, active_path(active), class:'active_titile', id:"active_{active_id}" %>
    </li>
  <% end %>
</ul>
<%= link_to "Create a New Active", new_active_path, class: "new_active" %>

app/views/actives/new.html.erb
<h1>Create a New Article</h1>
<%= form_for(@active) do |f| %>
  <ul>
  <% @active.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.file_field :photo %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/actives/show.html.erb
<h1><%= @active.title %></h1>
<p><%= @active.body %></p>
<%= link_to "Back to Actives List", actives_path %><br />
<%= link_to "delete", active_path(@active), method: :delete ,data: {confirm: "Really delete the article?"}%><br />
<%= link_to "edit", edit_active_path(@active) %>

<h3>Comments (<%= @active.comments.size %>)</h3>
<%= render partial: 'actives/comment', collection: @active.comments %>

<%= render partial: 'comments/form' %>

<p>
  Tags:
  <% @active.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<%= image_tag @active.photo, size: "300x200" %>

<p><%#= image_tag @active.image.url %></p>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_with model: [ @active, @active.comments.build ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash">
  <%= flash.notice %>
</p>
<%= yield %>

</body>
</html>

app/views/tags/show.html.erb
<h1>Actives Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.actives.each do |active| %>
    <li><%= link_to active.title, active_path(active) %></li>
  <% end %>
</ul>